//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTİTYEntities : DbContext
    {
        public DBCVENTİTYEntities()
            : base("name=DBCVENTİTYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Adres> tbl_Adres { get; set; }
        public virtual DbSet<tbl_Çalışmalarım> tbl_Çalışmalarım { get; set; }
        public virtual DbSet<tbl_Hakkımda> tbl_Hakkımda { get; set; }
        public virtual DbSet<tbl_İletişim> tbl_İletişim { get; set; }
        public virtual DbSet<tbl_Yetenekler> tbl_Yetenekler { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
    }
}
